# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sliding window mean
#'
#' Compute mean of each sliding window.
#'
#' @param x A vector of numeric values.
#' @param length An integer. Length of a window.
#' @param by An integer. Step between each window.
#' @param keep_cut A boolean. Indicate if the last uncompleted window should be kept or not.
sliding_window_mean <- function(x, length, by, keep_cut) {
    .Call(`_RSlidingWindow_sliding_window_mean`, x, length, by, keep_cut)
}

